# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b2e1a71338a44049a016a12d339b1b4d10b508ebfcac9863d88a240b02ccc9577e7858b99d9fcc98442a858a2e0c53a2bc39af5e1f8edd1413d1a2dfbf51de8

test:
  secret_key_base: d4282b7a957a06bc015ee718b72cca66c5b9338e66a7fd4488c3769ab67a0022e709c2c550b9c922d7bea891509028175f5b7d3b704b1aa6cfa2a45025399205

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
